use @types
smartive/generator-giuseppe pull request #10
Opened 2017-02-14 19:34 UTC by Kaffiend

havent really worked with generators, but from what i can decypher at a glance something like this i what i was meaning.

2017-02-14 19:54 UTC, Kaffiend commented
i think thats it, first time working on a generator. 😄

2017-02-15 06:54 UTC, buehler commented
Cool :-)

Would you mind to add a corresponding line to the changelog?
like
```md
#### Changed
- ...
```

2017-02-15 06:57 UTC, buehler requested changes
General good idea, I just have some small comments.

2017-02-15 06:57 UTC, buehler commented on app/index.ts
>              devTypings = [],
Those should be unused variables now right? (`devTypings` and `devGlobalTypings`)

2017-02-15 06:57 UTC, buehler commented on app/index.ts
>              devTypings = [],
Or more typings in general :-)

2017-02-15 06:57 UTC, buehler commented on app/templates/tsconfig.json
> +  "typeRoots": [
isn't this default by typescript? As I'm aware of, @types is the default folder to look for typings, do you really need to provide the `typeRoots` info?

2017-02-15 11:30 UTC, Kaffiend commented
I believe your right, i usually have it out of explicitness or if im doing mixed typings when there isnt any @types for a lib yet. Yes those should be unused variables now so they can be dropped out unless we encounter an issue with a typing and need to override with a legacy typing file

2017-02-15 16:41 UTC, mfeltscher commented
LGTM, @buehler WDYT? :shipit:

2017-02-16 08:37 UTC, buehler approved these changes

2017-02-16 08:37 UTC, buehler commented
Yep, :shipit: 
Thank you @Kaffiend

2017-02-16 08:37 UTC, merged